version: '2'
services:
  nginx:
      container_name: Nginx
      build: nginx
      network_mode: host
      ports:
        - '80:80'
        - '443:443'
      depends_on:
          - "app"
      environment:
        - DOMAIN_NAME=btp.my-domain.com
  gui:
        container_name: GUI
        build: gui
        network_mode: host
        ports:
          - "127.0.0.1:7770:7770"
        depends_on:
              - "app"
  app:
      container_name: APP
      build: app
      network_mode: host
      ports:
        - "127.0.0.1:7443:7443"
        - "127.0.0.1:7769:7769"
        - "127.0.0.1:7768:7768"

